// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"xiaohuasheng/internal/model"
)

type (
	IEvent interface {
		Create(ctx context.Context, in model.EventCreateInput) (out model.EventCreateOutput, err error)
		Delete(ctx context.Context, id uint) error
		Update(ctx context.Context, in model.EventUpdateInput) error
		GetList(ctx context.Context, in model.EventGetListInput) (out *model.EventGetListOutput, err error)
	}
)

var (
	localEvent IEvent
)

func Event() IEvent {
	if localEvent == nil {
		panic("implement not found for interface IEvent, forgot register?")
	}
	return localEvent
}

func RegisterEvent(i IEvent) {
	localEvent = i
}
